### ISSUE TITLE
 Add option for auth server key rotation keyAlgsAllowedForGeneration

### ISSUE THREAD

**Issue by moabu** [JanssenProject/docker-jans-certmanager#9]
This option will allow keys with specified algs to be generated, otherwise all algs will be assumed. 

Option needs to be added to the options of auth-server key rotation job.

Related issue:
https://github.com/JanssenProject/jans-auth-server/issues/74

**Comment by iromli** [comment]
Implemented in 4761760f498ef305b5acdc1c70deeeb88a44024a and a4ff039e66940ab67ad5bebf1cdc55081eab77c7
